[package]
name = "atlantic_example_contract"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"
integrity = "2.0.0"

[dev-dependencies]
snforge_std = "0.36.0"

[scripts]
test = "snforge test"